"""
Professional report generation
"""
from datetime import datetime
from typing import Dict, Any
import os

class ReportGenerator:
    """Generates professional security reports"""
    
    def __init__(self, reports_dir: str = "reports"):
        self.reports_dir = reports_dir
        os.makedirs(reports_dir, exist_ok=True)
    
    def generate_html_report(
        self,
        target: str,
        analysis: Dict[str, Any],
        ai_recommendations: str
    ) -> str:
        """Generate professional HTML report"""
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.reports_dir}/security_report_{target.replace('.', '_')}_{timestamp}.html"
        
        vuln_html = ""
        for vuln in analysis['vulnerabilities']:
            vuln_html += f"""<div class="vulnerability">
                <h4>{vuln['name']}</h4>
                <p><strong>Service:</strong> {vuln['service']} {vuln['version']}</p>
                <p><strong>Port:</strong> {vuln['port']}</p>
                <p><strong>CVE:</strong> {vuln['cve']}</p>
                <p><strong>Description:</strong> {vuln['description']}</p>
                <div style="margin-top: 10px;">
                    <span class="cvss">CVSS: {vuln['cvss']}</span>
                    <span class="severity {vuln['severity'].lower()}">{vuln['severity']}</span>
                </div>
            </div>"""
        
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Assessment Report - {target}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; }}
        .container {{ max-width: 1000px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px; border-radius: 10px; margin-bottom: 30px; }}
        .header h1 {{ font-size: 2.5em; margin-bottom: 10px; }}
        .header p {{ font-size: 1.1em; opacity: 0.9; }}
        .section {{ background: white; padding: 30px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .section h2 {{ color: #667eea; border-bottom: 3px solid #667eea; padding-bottom: 15px; margin-bottom: 20px; }}
        .risk-score {{ font-size: 3em; font-weight: bold; color: #ff6b6b; }}
        .vulnerability {{ background: #f9f9f9; padding: 20px; margin-bottom: 15px; border-left: 4px solid #ff6b6b; border-radius: 4px; }}
        .vulnerability h4 {{ color: #333; margin-bottom: 10px; }}
        .cvss {{ display: inline-block; padding: 5px 15px; background: #ff6b6b; color: white; border-radius: 20px; font-size: 0.9em; margin: 5px 5px 5px 0; }}
        .severity {{ display: inline-block; padding: 5px 15px; border-radius: 20px; font-size: 0.9em; margin: 5px 5px 5px 0; }}
        .critical {{ background: #ff6b6b; color: white; }}
        .high {{ background: #ffa500; color: white; }}
        .medium {{ background: #ffd700; color: #333; }}
        .low {{ background: #90ee90; color: #333; }}
        .recommendations {{ background: #e3f2fd; padding: 20px; border-radius: 5px; }}
        .footer {{ text-align: center; padding: 20px; color: #666; border-top: 1px solid #ddd; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔐 Security Assessment Report</h1>
            <p>Target: <strong>{target}</strong></p>
            <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <div class="section">
            <h2>📊 Executive Summary</h2>
            <p><strong>Overall Risk Score:</strong></p>
            <div class="risk-score">{analysis['risk_score']:.1f}/10.0</div>
            <p style="margin-top: 20px; color: #666;">
                This assessment identified <strong>{len(analysis['vulnerabilities'])}</strong> vulnerability/vulnerabilities
                across <strong>{analysis['total_ports']}</strong> open ports.
            </p>
        </div>
        
        <div class="section">
            <h2>🔍 Vulnerabilities Found</h2>
            {vuln_html if vuln_html else '<p>No vulnerabilities found!</p>'}
        </div>
        
        <div class="section recommendations">
            <h2>💡 AI-Generated Recommendations</h2>
            <div style="white-space: pre-wrap; line-height: 1.6; color: #333;">
{ai_recommendations}
            </div>
        </div>
        
        <div class="footer">
            <p>Generated by Autonomous Security Intelligence Agent</p>
            <p style="font-size: 0.9em; margin-top: 10px;">This report is confidential and for authorized use only.</p>
        </div>
    </div>
</body>
</html>"""
        
        with open(filename, 'w') as f:
            f.write(html_content)
        
        return filename
    
    def generate_text_report(
        self,
        target: str,
        analysis: Dict[str, Any],
        ai_recommendations: str
    ) -> str:
        """Generate plain text report"""
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.reports_dir}/security_report_{target.replace('.', '_')}_{timestamp}.txt"
        
        # Build vulnerabilities section
        vuln_section = ""
        if analysis['vulnerabilities']:
            for i, vuln in enumerate(analysis['vulnerabilities'], 1):
                vuln_section += f"""[{i}] {vuln['name']}
    Service: {vuln['service']} {vuln['version']}
    Port: {vuln['port']}
    CVSS Score: {vuln['cvss']}/10.0
    Severity: {vuln['severity']}
    CVE: {vuln['cve']}
    Description: {vuln['description']}

"""
        else:
            vuln_section = "No vulnerabilities found.\n"
        
        content = f"""{'='*80}
AUTONOMOUS SECURITY INTELLIGENCE AGENT
Security Assessment Report
{'='*80}

TARGET INFORMATION
{'─'*80}
Target: {target}
Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

EXECUTIVE SUMMARY
{'─'*80}
Overall Risk Score: {analysis['risk_score']:.1f}/10.0
Open Ports Found: {analysis['total_ports']}
Vulnerabilities Identified: {len(analysis['vulnerabilities'])}

VULNERABILITIES
{'─'*80}
{vuln_section}

AI-GENERATED RECOMMENDATIONS
{'─'*80}
{ai_recommendations}

NEXT STEPS
{'─'*80}
1. Review all identified vulnerabilities
2. Prioritize by severity and exploitability
3. Apply recommended patches
4. Re-scan after remediation
5. Document all changes

{'='*80}
Generated by Autonomous Security Intelligence Agent
Confidential - Authorized Use Only
{'='*80}"""
        
        with open(filename, 'w') as f:
            f.write(content)
        
        return filename
